/**
 * proposal-html — server-side HTML renderer for client proposals.
 *
 * Produces a single self-contained .html document (inline styles)
 * that the firm sends to the client. The artifact is the source of
 * truth — once generated, edits to the underlying work_items don't
 * affect it. To revise, regenerate.
 *
 * Print-friendly @media rules let the client hit Cmd-P and get a
 * presentable PDF without us needing a headless browser server-side.
 * Real HTML → PDF rasterization is a follow-up.
 */

export interface ProposalRenderLine {
  sectionLabel: string | null;
  ref: string | null;
  description: string;
  qty: string | null;
  unit: string | null;
  unitPrice: string | null;
  total: string | null;
  rooms: string[];
}

export interface ProposalRenderInput {
  /** Public number like "PROP-2026-0001". */
  number: string;
  projectName: string;
  projectAddress: string | null;
  clientName: string | null;
  title: string;
  introText: string | null;
  expiresAt: string | null;
  currency: string;
  /** Date string YYYY-MM-DD. */
  issuedOn: string;
  lines: ProposalRenderLine[];
  /** Pre-formatted bottom-line total string (already includes currency). */
  totalFormatted: string;
  /** Org display name for the header. */
  orgName: string;
}

/**
 * Render the proposal to an HTML string. No DB or storage calls
 * here — kept pure so it's easy to test and to preview from the UI
 * without persisting anything.
 */
export function renderProposalHtml(input: ProposalRenderInput): string {
  const grouped = groupBySection(input.lines);

  const sections = grouped
    .map(
      (g) => `
      <section class="section">
        ${g.label ? `<h2 class="section-label">${escape(g.label)}</h2>` : ""}
        <table class="lines">
          <thead>
            <tr>
              <th class="ref">Ref</th>
              <th class="desc">Description</th>
              <th class="qty">Qty</th>
              <th class="price">Unit</th>
              <th class="total">Total</th>
            </tr>
          </thead>
          <tbody>
            ${g.lines.map(renderLineRow).join("")}
          </tbody>
        </table>
      </section>
    `,
    )
    .join("");

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>${escape(input.title)} · ${escape(input.number)}</title>
  <meta name="generator" content="Beamy">
  <style>${STYLES}</style>
</head>
<body>
  <article class="proposal">
    <header class="title-block">
      <div class="stamp">
        <span class="number">${escape(input.number)}</span>
        <span class="sep">|</span>
        <span class="issued">issued ${escape(input.issuedOn)}</span>
      </div>
      <h1 class="title">${escape(input.title)}</h1>
      <dl class="facts">
        <div class="fact"><dt>Project</dt><dd>${escape(input.projectName)}</dd></div>
        ${input.projectAddress ? `<div class="fact"><dt>Address</dt><dd>${escape(input.projectAddress)}</dd></div>` : ""}
        ${input.clientName ? `<div class="fact"><dt>Client</dt><dd>${escape(input.clientName)}</dd></div>` : ""}
        ${input.expiresAt ? `<div class="fact"><dt>Expires</dt><dd>${escape(input.expiresAt)}</dd></div>` : ""}
        <div class="fact"><dt>Currency</dt><dd>${escape(input.currency)}</dd></div>
      </dl>
    </header>

    ${input.introText ? `<section class="intro"><p>${escape(input.introText).replace(/\n/g, "<br>")}</p></section>` : ""}

    ${sections}

    <footer class="bottom-line">
      <div class="total-row">
        <span class="label">Total</span>
        <span class="value">${escape(input.totalFormatted)}</span>
      </div>
    </footer>

    <p class="sig">Prepared by ${escape(input.orgName)} — generated by Beamy.</p>
  </article>
</body>
</html>`;
}

function renderLineRow(line: ProposalRenderLine): string {
  return `
    <tr>
      <td class="ref">${line.ref ? escape(line.ref) : ""}</td>
      <td class="desc">
        <div class="desc-text">${escape(line.description)}</div>
        ${
          line.rooms.length > 0
            ? `<div class="rooms">${line.rooms.map((r) => `<span class="room">${escape(r)}</span>`).join("")}</div>`
            : ""
        }
      </td>
      <td class="qty">${line.qty ? escape(line.qty) + (line.unit ? ` ${escape(line.unit)}` : "") : ""}</td>
      <td class="price">${line.unitPrice ? escape(line.unitPrice) : ""}</td>
      <td class="total">${line.total ? escape(line.total) : ""}</td>
    </tr>
  `;
}

function groupBySection(
  lines: ProposalRenderLine[],
): { label: string | null; lines: ProposalRenderLine[] }[] {
  const groups: { label: string | null; lines: ProposalRenderLine[] }[] = [];
  let current: { label: string | null; lines: ProposalRenderLine[] } | null =
    null;
  for (const line of lines) {
    if (!current || current.label !== line.sectionLabel) {
      current = { label: line.sectionLabel, lines: [] };
      groups.push(current);
    }
    current.lines.push(line);
  }
  return groups;
}

function escape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const STYLES = `
  :root {
    --ink: #1f2a3a;
    --rule: #d8dde6;
    --paper: #ffffff;
    --paper-2: #f7f8fa;
    --muted: #6b7588;
    --accent: #d97706;
  }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; background: var(--paper-2); color: var(--ink); font-family: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.45; }
  .proposal { max-width: 880px; margin: 32px auto; background: var(--paper); border: 1px solid var(--rule); }

  .title-block { padding: 24px 32px; border-bottom: 1px solid var(--rule); }
  .stamp { font-family: SFMono-Regular, ui-monospace, Menlo, monospace; font-size: 10px; letter-spacing: 0.15em; text-transform: uppercase; color: var(--muted); }
  .stamp .number { color: var(--ink); font-weight: 600; }
  .stamp .sep { margin: 0 8px; color: var(--rule); }
  .title { margin: 12px 0 16px; font-size: 28px; font-weight: 600; letter-spacing: -0.01em; }

  .facts { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 1px; background: var(--rule); border-top: 1px solid var(--rule); border-bottom: 1px solid var(--rule); margin: 16px -32px 0; padding: 0; }
  .facts .fact { background: var(--paper); padding: 10px 32px; }
  .facts dt { font-family: SFMono-Regular, ui-monospace, Menlo, monospace; font-size: 9px; letter-spacing: 0.15em; text-transform: uppercase; color: var(--muted); margin: 0; }
  .facts dd { font-size: 13px; font-weight: 500; margin: 4px 0 0; }

  .intro { padding: 20px 32px; border-bottom: 1px solid var(--rule); }
  .intro p { margin: 0; color: var(--ink); }

  .section { padding: 20px 32px; border-bottom: 1px solid var(--rule); }
  .section-label { font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: var(--accent); margin: 0 0 12px; }
  table.lines { width: 100%; border-collapse: collapse; }
  table.lines th { text-align: left; font-family: SFMono-Regular, ui-monospace, Menlo, monospace; font-size: 9px; letter-spacing: 0.12em; text-transform: uppercase; color: var(--muted); padding: 6px 8px; border-bottom: 1px solid var(--rule); font-weight: 600; }
  table.lines td { padding: 10px 8px; vertical-align: top; border-bottom: 1px solid var(--paper-2); }
  table.lines .ref { width: 60px; font-family: SFMono-Regular, ui-monospace, Menlo, monospace; font-size: 11px; color: var(--muted); }
  table.lines .desc { }
  table.lines .desc-text { font-weight: 500; }
  table.lines .rooms { margin-top: 4px; }
  table.lines .room { display: inline-block; margin-right: 4px; padding: 1px 6px; background: var(--paper-2); border-radius: 999px; font-size: 10px; font-family: SFMono-Regular, ui-monospace, Menlo, monospace; text-transform: uppercase; letter-spacing: 0.04em; color: var(--muted); }
  table.lines .qty { width: 90px; text-align: right; font-family: SFMono-Regular, ui-monospace, Menlo, monospace; }
  table.lines .price { width: 120px; text-align: right; font-family: SFMono-Regular, ui-monospace, Menlo, monospace; }
  table.lines .total { width: 140px; text-align: right; font-family: SFMono-Regular, ui-monospace, Menlo, monospace; font-weight: 600; }

  .bottom-line { padding: 20px 32px; background: var(--paper-2); border-top: 2px solid var(--ink); }
  .total-row { display: flex; justify-content: space-between; align-items: baseline; }
  .total-row .label { font-family: SFMono-Regular, ui-monospace, Menlo, monospace; font-size: 11px; letter-spacing: 0.12em; text-transform: uppercase; color: var(--muted); }
  .total-row .value { font-size: 24px; font-weight: 600; font-family: SFMono-Regular, ui-monospace, Menlo, monospace; }

  .sig { padding: 16px 32px 24px; color: var(--muted); font-size: 11px; }

  @media print {
    body, html { background: var(--paper); }
    .proposal { margin: 0; border: 0; max-width: none; }
    .section, .title-block, .intro, .bottom-line { page-break-inside: avoid; }
  }
`;
