import {
  date,
  index,
  integer,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { orgs } from "./orgs";
import { projects } from "./projects";
import { workItems } from "./work-items";

/**
 * change_orders — formal scope/budget change document. Generated by
 * the firm, sent to the client, signed (or not) by the client. When
 * approved, the line-level changes apply transactionally to the
 * project's work_items.
 *
 * `number` is the public CO number, sequential per-org-per-year
 * (`CO-2026-0001`). Unique within an org.
 *
 * Lifecycle: `drafted → sent → approved | rejected | void`. Approval
 * is a one-way door: the moment it flips to `approved`, line deltas
 * land on work_items and stamp `decided_at`. `void` is a
 * documentation status — it does NOT unwind an approved CO. To
 * reverse, you create a corrective CO.
 *
 * `total_delta_amount` can be negative (deductive change order). The
 * currency is single-CO for v1; a mixed-currency CO is uncommon and
 * adds modeling complexity we don't need yet.
 */
export const changeOrders = pgTable(
  "change_orders",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => orgs.id, { onDelete: "cascade" }),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    /** Public CO number: "CO-2026-0001". Unique within an org. */
    number: text("number").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    status: text("status", {
      enum: ["drafted", "sent", "approved", "rejected", "void"],
    })
      .notNull()
      .default("drafted"),
    sentAt: date("sent_at"),
    decidedAt: date("decided_at"),
    /** Free-form name of who approved (client signatory name). */
    decidedBy: text("decided_by"),
    /**
     * Total money impact across all lines, frozen at CO creation.
     * Can be negative (deductive CO). UI computes the suggested
     * value from the sum of line.totalDeltaAmount; caller can
     * override if there's a reason (rounding, lump-sum framing).
     */
    totalDeltaAmount: numeric("total_delta_amount", {
      precision: 14,
      scale: 2,
    }).notNull(),
    totalDeltaCurrency: text("total_delta_currency").notNull(),
    /** The signed PDF, when uploaded. Links to documents row. */
    signedDocumentId: uuid("signed_document_id"),
    notes: text("notes"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => ({
    byProject: index("change_orders_by_project").on(table.projectId),
    byOrgStatus: index("change_orders_by_org_status").on(
      table.orgId,
      table.status,
    ),
    /** CO numbers are unique within an org. */
    uniqOrgNumber: uniqueIndex("change_orders_org_number_unique").on(
      table.orgId,
      table.number,
    ),
  }),
);

export type ChangeOrder = typeof changeOrders.$inferSelect;
export type NewChangeOrder = typeof changeOrders.$inferInsert;

/**
 * change_order_lines — the actual scope changes. Each line is one
 * of three kinds:
 *
 *   - `add`: a brand-new work_item. `work_item_id` is null at
 *     creation. On approval, a work_item is created from the
 *     line's fields and `created_work_item_id` is stamped here
 *     for the audit trail.
 *
 *   - `modify`: an existing work_item changes. `work_item_id` is
 *     required. On approval, the work_item gets the line's
 *     "after-state" fields applied (any non-null field is set).
 *
 *   - `remove`: an existing work_item is cancelled. `work_item_id`
 *     is required. On approval, the work_item's status flips to
 *     "cancelled".
 *
 * The "after-state" model: a `modify` line stores the values the
 * work_item should HAVE after the CO applies, not deltas off the
 * current state. Simpler to read on the printed artifact ("Item
 * V14 is now 5 ea at $1,500"). `totalDeltaAmount` snapshots the
 * money impact, computed at creation time and frozen.
 */
export const changeOrderLines = pgTable(
  "change_order_lines",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    changeOrderId: uuid("change_order_id")
      .notNull()
      .references(() => changeOrders.id, { onDelete: "cascade" }),
    kind: text("kind", { enum: ["add", "modify", "remove"] }).notNull(),
    /** Required for modify/remove; null for add. */
    workItemId: uuid("work_item_id").references(() => workItems.id, {
      onDelete: "set null",
    }),
    /**
     * For `add` lines, stamped at approval with the freshly-created
     * work_item id. Lets the UI deep-link from the CO line to the
     * resulting work item.
     */
    createdWorkItemId: uuid("created_work_item_id").references(
      () => workItems.id,
      { onDelete: "set null" },
    ),
    displayOrder: integer("display_order").notNull().default(0),
    /** After-state fields. Null = "no change to this field" on modify. */
    description: text("description"),
    qty: numeric("qty", { precision: 14, scale: 4 }),
    unit: text("unit"),
    unitPriceAmount: numeric("unit_price_amount", { precision: 14, scale: 2 }),
    unitPriceCurrency: text("unit_price_currency"),
    /**
     * Money impact of this line, frozen at CO creation. Can be
     * negative. The CO's total_delta is the sum of these.
     */
    totalDeltaAmount: numeric("total_delta_amount", {
      precision: 14,
      scale: 2,
    }).notNull(),
    notes: text("notes"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    byChangeOrder: index("change_order_lines_by_change_order").on(
      table.changeOrderId,
      table.displayOrder,
    ),
    byWorkItem: index("change_order_lines_by_work_item").on(table.workItemId),
  }),
);

export type ChangeOrderLine = typeof changeOrderLines.$inferSelect;
export type NewChangeOrderLine = typeof changeOrderLines.$inferInsert;
