/**
 * One-shot importer for the Rubén Darío 123 proposal.
 *
 * Reads `Propuesta/00_dashboard/data/proposal.js` from the user's
 * CursorProjects folder, then seeds the Beamy "Ruben Dario" project with:
 *   - all 16 rooms from the proposal
 *   - all 16 vendors (+ vendor contacts) from the quote list
 *   - one `bids` row per vendor quote
 *   - one `work_items` row per line item, linked to the parent bid
 *
 * Idempotent: re-running checks for existing rows by natural key and
 * skips inserts that would duplicate. Run via:
 *
 *   pnpm db:import-propuesta
 *
 * The proposal.js file is JS (window.PROPOSAL = {...};) so we read it as
 * text, strip the assignment prefix, strip the trailing semicolon, and
 * parse the JSON middle. The file is generated by the dashboard editor
 * and never contains JS expressions — pure data.
 */
import { readFileSync } from "node:fs";
import { and, eq } from "drizzle-orm";
import {
  bids,
  getDb,
  projects,
  rooms,
  vendorContacts,
  vendors,
  workItems,
} from "../src/index";

const DEV_ORG_ID = "00000000-0000-0000-0000-000000000010";
const DEV_USER_ID = "00000000-0000-0000-0000-000000000001";
const ACTOR = `user:${DEV_USER_ID}`;
const PROPOSAL_PATH =
  "/Users/adrianbazbaz/CursorProjects/Propuesta/00_dashboard/data/proposal.js";

type Proposal = {
  project: {
    address: string;
    client: string;
    designer: string;
    prepared: string;
    fx: { USD_MXN: number; EUR_MXN: number; MXN_MXN: number; note: string };
  };
  trades: Array<{ id: string; label: string; short: string }>;
  rooms: Array<{ id: string; label: string }>;
  vendors: Array<{
    id: string;
    name: string;
    trade_id: string;
    addressee: string;
    contact: {
      name?: string;
      phone?: string;
      email?: string;
      web?: string;
    };
    quote_number: string;
    quote_date: string;
    validity_note: string;
    currency: string;
    subtotal: number;
    iva: number;
    total_as_quoted: number;
    total_mxn: number;
    iva_included: boolean;
    source_file: string;
    flags: string[];
    line_items: Array<{
      ref: string;
      description: string;
      qty: number;
      unit_price: number;
      total: number;
      currency: string;
      room_ids: string[];
    }>;
  }>;
};

function normalizeDate(s: string | null | undefined): string | null {
  if (!s) return null;
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;
  if (/^\d{4}-\d{2}$/.test(s)) return `${s}-01`;
  if (/^\d{4}$/.test(s)) return `${s}-01-01`;
  return null;
}

function readProposal(): Proposal {
  const raw = readFileSync(PROPOSAL_PATH, "utf8");
  const start = raw.indexOf("{");
  const end = raw.lastIndexOf("}");
  if (start < 0 || end < 0) throw new Error("Could not locate JSON in proposal.js");
  const json = raw.slice(start, end + 1);
  return JSON.parse(json) as Proposal;
}

async function findProject(name: string) {
  const db = getDb();
  const rows = await db
    .select()
    .from(projects)
    .where(and(eq(projects.orgId, DEV_ORG_ID), eq(projects.name, name)))
    .limit(1);
  return rows[0] ?? null;
}

async function importRooms(projectId: string, proposal: Proposal) {
  const db = getDb();
  const tradeLabels = new Map(proposal.trades.map((t) => [t.id, t.label]));

  let inserted = 0;
  let existing = 0;
  for (const r of proposal.rooms) {
    const found = await db
      .select({ id: rooms.id })
      .from(rooms)
      .where(and(eq(rooms.projectId, projectId), eq(rooms.name, r.label)))
      .limit(1);
    if (found[0]) {
      existing++;
      continue;
    }
    // Pick a roomType bucket from a few simple heuristics on the label.
    const lower = r.label.toLowerCase();
    let roomType: string = "other";
    if (lower.includes("baño")) roomType = "bath";
    else if (lower.includes("recámara") || lower.includes("recamara"))
      roomType = "bedroom";
    else if (lower.includes("cocina")) roomType = "kitchen";
    else if (lower.includes("comedor")) roomType = "dining";
    else if (lower.includes("sala") || lower.includes("estancia"))
      roomType = "living";
    else if (lower.includes("vestidor")) roomType = "other";
    else if (lower.includes("terraza")) roomType = "exterior";
    else if (lower.includes("acceso") || lower.includes("vestíbulo"))
      roomType = "hallway";

    await db.insert(rooms).values({
      orgId: DEV_ORG_ID,
      projectId,
      name: r.label,
      roomType: roomType as never,
      createdBy: ACTOR,
      updatedBy: ACTOR,
    });
    inserted++;
  }
  console.log(`  rooms: +${inserted} new, ${existing} existing`);
  // Build a map of proposal room id → DB room id (for line items later if we choose to link).
  const all = await db
    .select({ id: rooms.id, name: rooms.name })
    .from(rooms)
    .where(eq(rooms.projectId, projectId));
  const byProposalId = new Map<string, string>();
  for (const r of proposal.rooms) {
    const match = all.find((x) => x.name === r.label);
    if (match) byProposalId.set(r.id, match.id);
  }
  return byProposalId;
}

async function importVendors(proposal: Proposal) {
  const db = getDb();
  const tradeLabels = new Map(proposal.trades.map((t) => [t.id, t.label]));
  const byProposalId = new Map<string, string>();
  let inserted = 0;
  let existing = 0;

  for (const v of proposal.vendors) {
    const found = await db
      .select({ id: vendors.id })
      .from(vendors)
      .where(and(eq(vendors.orgId, DEV_ORG_ID), eq(vendors.name, v.name)))
      .limit(1);

    let vendorId: string;
    if (found[0]) {
      vendorId = found[0].id;
      existing++;
    } else {
      const [row] = await db
        .insert(vendors)
        .values({
          orgId: DEV_ORG_ID,
          name: v.name,
          trade: tradeLabels.get(v.trade_id) ?? v.trade_id,
          primaryContact: v.contact?.name ?? null,
          email: v.contact?.email ?? null,
          phone: v.contact?.phone ?? null,
          status: "active",
          createdBy: ACTOR,
          updatedBy: ACTOR,
        })
        .returning({ id: vendors.id });
      if (!row) throw new Error(`Failed to insert vendor ${v.name}`);
      vendorId = row.id;
      inserted++;

      // Add contact row if we have a named person + email/phone.
      if (v.contact?.name && (v.contact.email || v.contact.phone)) {
        await db.insert(vendorContacts).values({
          orgId: DEV_ORG_ID,
          vendorId,
          name: v.contact.name,
          email: v.contact.email ?? null,
          phone: v.contact.phone ?? null,
          isPrimary: true,
          createdBy: ACTOR,
          updatedBy: ACTOR,
        });
      }
    }
    byProposalId.set(v.id, vendorId);
  }
  console.log(`  vendors: +${inserted} new, ${existing} existing`);
  return byProposalId;
}

async function importBidsAndLines(
  projectId: string,
  proposal: Proposal,
  vendorMap: Map<string, string>,
) {
  const db = getDb();
  const tradeLabels = new Map(proposal.trades.map((t) => [t.id, t.label]));
  let bidsInserted = 0;
  let bidsExisting = 0;
  let linesInserted = 0;

  for (const v of proposal.vendors) {
    const vendorId = vendorMap.get(v.id);
    if (!vendorId) continue;

    const found = await db
      .select({ id: bids.id })
      .from(bids)
      .where(
        and(
          eq(bids.projectId, projectId),
          eq(bids.vendorId, vendorId),
          eq(bids.bidNumber, v.quote_number),
        ),
      )
      .limit(1);

    let bidId: string;
    if (found[0]) {
      bidId = found[0].id;
      bidsExisting++;
    } else {
      const [row] = await db
        .insert(bids)
        .values({
          orgId: DEV_ORG_ID,
          projectId,
          vendorId,
          trade: tradeLabels.get(v.trade_id) ?? v.trade_id,
          bidNumber: v.quote_number,
          bidDate: normalizeDate(v.quote_date),
          subtotalAmount: v.subtotal != null ? String(v.subtotal) : null,
          ivaAmount: v.iva != null ? String(v.iva) : null,
          totalAmount:
            v.total_as_quoted != null ? String(v.total_as_quoted) : null,
          currency: v.currency,
          ivaIncluded: v.iva_included,
          status: "comparing",
          flags: v.flags ?? [],
          notes: v.validity_note && v.validity_note !== "—" ? v.validity_note : null,
          createdBy: ACTOR,
          updatedBy: ACTOR,
        })
        .returning({ id: bids.id });
      if (!row) throw new Error(`Failed to insert bid for ${v.name}`);
      bidId = row.id;
      bidsInserted++;
    }

    // Line items → work_items linked to the bid.
    for (const li of v.line_items ?? []) {
      // Match existing by (projectId, bidId, ref).
      const existing = await db
        .select({ id: workItems.id })
        .from(workItems)
        .where(
          and(
            eq(workItems.projectId, projectId),
            eq(workItems.bidId, bidId),
            eq(workItems.ref, li.ref),
          ),
        )
        .limit(1);
      if (existing[0]) continue;

      await db.insert(workItems).values({
        orgId: DEV_ORG_ID,
        projectId,
        bidId,
        vendorId,
        trade: tradeLabels.get(v.trade_id) ?? v.trade_id,
        ref: li.ref,
        description: li.description,
        qty: li.qty != null ? String(li.qty) : null,
        unit: null,
        unitPriceAmount:
          li.unit_price != null ? String(li.unit_price) : null,
        unitPriceCurrency: li.currency,
        totalAmount: li.total != null ? String(li.total) : null,
        totalCurrency: li.currency,
        status: "specified",
        createdBy: ACTOR,
        updatedBy: ACTOR,
      });
      linesInserted++;
    }
  }
  console.log(
    `  bids: +${bidsInserted} new, ${bidsExisting} existing  ·  work_items: +${linesInserted} new`,
  );
}

async function main() {
  console.log("Reading proposal.js …");
  const proposal = readProposal();
  console.log(
    `  ${proposal.rooms.length} rooms · ${proposal.vendors.length} vendors · ${proposal.vendors.reduce((n, v) => n + (v.line_items?.length ?? 0), 0)} line items`,
  );

  const project = await findProject("Ruben Dario");
  if (!project) {
    throw new Error(
      'Project "Ruben Dario" not found in org. Create it in the UI first.',
    );
  }
  console.log(`Importing into project ${project.id} (${project.name})`);

  console.log("Rooms…");
  await importRooms(project.id, proposal);

  console.log("Vendors…");
  const vendorMap = await importVendors(proposal);

  console.log("Bids + line items…");
  await importBidsAndLines(project.id, proposal, vendorMap);

  console.log("Done.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
